spring.application.name=User-Service
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=ThisIsAVeryLongSecretKeyForJWTSigningPurpose123456
jwt.expiration=86400000